name: API Deploy

on:
  push:
    branches:
      - develop
    paths:
      - "api/**"
  workflow_dispatch:

jobs:
  build-and-test:
    name: "Build & Test API"
    runs-on: ubuntu-latest
    outputs:
      build_status: ${{ steps.build.outcome }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/homolog" ]]; then
            echo "ENVIRONMENT=hml" >> $GITHUB_ENV
          fi

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          cd api
          npm install

      - name: Run Tests with Coverage
        run: |
          cd api
          npm run test:cov

      - name: Save Test Coverage as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: api/coverage
          retention-days: 5

      - name: Build API
        id: build
        run: |
          cd api
          npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Serverless Login
        run: |
          npx serverless login --access-key ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Package with Serverless Framework
        run: |
          cd api
          npx serverless package --stage ${{ env.ENVIRONMENT }}

      - name: Save Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-build
          path: api/.serverless
          retention-days: 5

  deploy-api:
    name: "Deploy API"
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/homolog" ]]; then
            echo "ENVIRONMENT=hml" >> $GITHUB_ENV
          fi

      - name: Download API Build
        uses: actions/download-artifact@v4
        with:
          name: api-build
          path: api/.serverless

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Serverless Login
        run: |
          npx serverless login --access-key ${{ secrets.SERVERLESS_ACCESS_KEY }}

      - name: Deploy with Serverless Framework (Only with Approval)
        run: |
          cd api
          npx serverless deploy --stage ${{ env.ENVIRONMENT }}
