name: Infrastructure Deploy

on:
  push:
    branches:
      - develop
    paths:
      - "infrastructure/**"
  workflow_dispatch:

jobs:
  terraform-plan:
    name: "Terraform Plan"
    runs-on: ubuntu-latest
    outputs:
      plan_status: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/homolog" ]]; then
            echo "ENVIRONMENT=hml" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Initialize Terraform
        run: |
          cd infrastructure
          terraform init --backend-config=envs/${{ env.ENVIRONMENT }}.backend.config

      - name: Terraform Plan
        id: plan
        run: |
          cd infrastructure
          terraform plan --var-file=envs/${{ env.ENVIRONMENT }}.tfvars -out=tfplan

      - name: Save Plan as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infrastructure/tfplan
          retention-days: 5

  terraform-apply:
    name: "Terraform Apply"
    needs: terraform-plan
    runs-on: ubuntu-latest
    environment: deploy-infrastructure

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Environment Variable
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "ENVIRONMENT=prd" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/develop" ]]; then
            echo "ENVIRONMENT=dev" >> $GITHUB_ENV
          elif [[ "${{ github.ref }}" == "refs/heads/homolog" ]]; then
            echo "ENVIRONMENT=hml" >> $GITHUB_ENV
          fi

      - name: Download Saved Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-plan
          path: tfplan

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Apply Terraform (Only with Approval)
        run: |
          cd infrastructure
          terraform apply --auto-approve tfplan --var-file=envs/${{ env.ENVIRONMENT }}.tfvars
